from fastapi import APIRouter, HTTPException
from models import MentionsRequest
from dashboard_menu.mentions import list_of_mentions
import math

router = APIRouter()

def sanitize_float(value):
    """Handle non-finite float values for JSON serialization"""
    if value is None:
        return None
    if isinstance(value, float):
        if math.isnan(value) or math.isinf(value):
            return None
    return value

def sanitize_data(data):
    """Recursively sanitize all float values in the data structure"""
    if isinstance(data, dict):
        return {k: sanitize_data(v) for k, v in data.items()}
    elif isinstance(data, list):
        return [sanitize_data(item) for item in data]
    elif isinstance(data, float):
        return sanitize_float(data)
    return data

@router.post("/api/mentions", tags=["Dashboard Menu"])
async def get_mentions(request: MentionsRequest):
    return {
            "status": "success",
            "data": [
                {
                "username": "r/indonesia/",
                "followers_user": "",
                "likes_user": "",
                "influence_score": "",
                "link_post": "https://www.reddit.com/r/indonesia/comments/28mu2e/kadins_kamar_dagang_dan_industri_unofficial/",
                "post_caption": "Kadin's (Kamar Dagang dan Industri) unofficial presidential debate live commenting thread. It's airing on both MetroTV *and TVOne.",
                "comments": 70,
                "likes": "",
                "shares": "",
                "favorites": "",
                "reposts": "",
                "views": "",
                "retweets": "",
                "replies": "",
                "votes": 3,
                "user_image_url": "https://styles.redditmedia.com/t5_2qkte/styles/communityIcon_fly81d3k0ij21.png",
                "viral_score": 169.27461339178927,
                "post_created_at": "2014-06-20 11:45:27",
                "sentiment": "neutral",
                "channel": "reddit"
                },
                {
                "username": "r/KGBTR/",
                "followers_user": "",
                "likes_user": "",
                "influence_score": "",
                "link_post": "https://www.reddit.com/r/KGBTR/comments/zqjkvs/toplumun_ilerlemsi_için_kadin_mi_daha_önemlidir/",
                "post_caption": "TOPLUMUN İLERLEMSİ İÇİN KADIN MI DAHA ÖNEMLİDİR YOKSA ERKEK Mİ?",
                "comments": 67,
                "likes": 0,
                "shares": 0,
                "favorites": 0,
                "reposts": 0,
                "views": 0,
                "retweets": 0,
                "replies": 0,
                "votes": 0,
                "user_image_url": "https://styles.redditmedia.com/t5_12t6sw/styles/communityIcon_qff9s3h0z8wc1.png",
                "viral_score": 157.76747817951718,
                "post_created_at": "2022-12-20 09:03:00",
                "sentiment": "neutral",
                "channel": "reddit"
                },
                {
                "username": "r/KGBTR/",
                "followers_user": "",
                "likes_user": "",
                "influence_score": "",
                "link_post": "https://www.reddit.com/r/KGBTR/comments/15rrp1e/31_cektiginiz_en_guzel_kadin_kimdi/",
                "post_caption": "31 cektiginiz en guzel kadin kimdi",
                "comments": 112,
                "likes": 26,
                "shares": 1,
                "favorites": 3,
                "reposts": 0,
                "views": 0,
                "retweets": 0,
                "replies": 0,
                "votes": 0,
                "user_image_url": "https://styles.redditmedia.com/t5_12t6sw/styles/communityIcon_qff9s3h0z8wc1.png",
                "viral_score": 139.39035280871735,
                "post_created_at": "2023-08-15 12:44:46",
                "sentiment": "negative",
                "channel": "reddit"
                },
                {
                "username": "anindyabakrie",
                "followers_user": "",
                "likes_user": "",
                "influence_score": 10,
                "link_post": "https://www.instagram.com/p/CO6cwYfBxPQ/",
                "post_caption": "Profil Anindya Bakrie atau yang akrab disapa ANIN, Calon Ketua Umum Kadin Indonesia.Kehidupan, pendidikan, pengalaman membangun bisnis dan berorganisasi.#AninUntukKadin #KadinBer1 #MajuBersamaAnin #Kadin #KadinIndonesia #MunasKadin #ProfilAnin",
                "comments": 211,
                "likes": 2,
                "shares": "",
                "favorites": "",
                "reposts": "",
                "views": "",
                "retweets": "",
                "replies": "",
                "votes": "",
                "user_image_url": "https://instagram.fbdo9-1.fna.fbcdn.net/v/t51.2885-19/191877176_3526961850862463_7541477850624359981_n.jpg?stp=dst-jpg_s150x150_tt6&_nc_ht=instagram.fbdo9-1.fna.fbcdn.net&_nc_cat=111&_nc_oc=Q6cZ2AHdtrSiF-CQvRpRYjlW0_Mnyj94lX6jZTPjghL3GZjJk_tnMNO2SMGWJJb9ltrFsi8&_nc_ohc=ZwigW6Do_MUQ7kNvgGKE60A&_nc_gid=TSyJ4xvrhXX7tqLyk2Htpg&edm=APs17CUBAAAA&ccb=7-5&oh=00_AYFloAaTH-qdOPGS--HLTMxg38n4lEU71V93lRwHc05Qcg&oe=67DE6740&_nc_sid=10d13b",
                "viral_score": 120.05901754282792,
                "post_created_at": "2021-05-16 00:16:14",
                "sentiment": "neutral",
                "channel": "instagram"
                },
                {
                "username": "r/dewrim/",
                "followers_user": "",
                "likes_user": "",
                "influence_score": "",
                "link_post": "https://www.reddit.com/r/dewrim/comments/1grynha/aşiğim_sana_be_kadin_yarrak_gibi_edit_ama_sadece/",
                "post_caption": "AŞIĞIM SANA BE KADIN (yarrak gibi edit ama sadece bu var)",
                "comments": 45,
                "likes": 0,
                "shares": 0,
                "favorites": 0,
                "reposts": 0,
                "views": 0,
                "retweets": 0,
                "replies": 0,
                "votes": 0,
                "user_image_url": "https://styles.redditmedia.com/t5_718psx/styles/communityIcon_5l9ztlajh23e1.png",
                "viral_score": 107.00108685380424,
                "post_created_at": "2024-11-15 15:19:04",
                "sentiment": "neutral",
                "channel": "reddit"
                },
                {
                "username": "r/KGBTR/",
                "followers_user": "",
                "likes_user": "",
                "influence_score": "",
                "link_post": "https://www.reddit.com/r/KGBTR/comments/w7iw2p/her_kadin_sağliklidir_diyen_feminist_orospu/",
                "post_caption": "HER KADIN SAĞLIKLIDIR DİYEN FEMİNİST OROSPU ÇOCUKLARI İÇİN HORRRTTT",
                "comments": 146,
                "likes": 2030,
                "shares": 102,
                "favorites": 203,
                "reposts": 0,
                "views": 0,
                "retweets": 0,
                "replies": 0,
                "votes": 0,
                "user_image_url": "https://styles.redditmedia.com/t5_12t6sw/styles/communityIcon_qff9s3h0z8wc1.png",
                "viral_score": 101.46049168397687,
                "post_created_at": "2022-07-25 07:55:24",
                "sentiment": "negative",
                "channel": "reddit"
                },
                {
                "username": "r/KGBTR/",
                "followers_user": "",
                "likes_user": "",
                "influence_score": "",
                "link_post": "https://www.reddit.com/r/KGBTR/comments/unj62e/istanbul_aqua_floryada_calisan_bir_kadin/",
                "post_caption": "Istanbul Aqua Florya’da calisan bir kadin kendisini gizlice kayda alan orospu evladi tacizci multecinin telefonunu parcaliyor",
                "comments": 96,
                "likes": 2332,
                "shares": 117,
                "favorites": 233,
                "reposts": 0,
                "views": 0,
                "retweets": 0,
                "replies": 0,
                "votes": 0,
                "user_image_url": "https://styles.redditmedia.com/t5_12t6sw/styles/communityIcon_qff9s3h0z8wc1.png",
                "viral_score": 97.22575357826176,
                "post_created_at": "2022-05-11 20:29:28",
                "sentiment": "negative",
                "channel": "reddit"
                },
                {
                "username": "wartaekonomi",
                "followers_user": "",
                "likes_user": "",
                "influence_score": "",
                "link_post": "https://www.instagram.com/p/DHLImGothsZ/",
                "post_caption": "Dikenal sebagai salah satu pengusaha terkaya di Kalimantan, Haji Isam sukses membangun Jhonlin Group yang bergerak di sektor batu bara dan perkebunan. Ia pemilik PT Jhonlin Baratama, yang kini menjadi pemain utama di industri tambang dengan produksi 400.000 ton batu bara per bulan.Kini, Haji Isam resmi diangkat sebagai Anggota Dewan Penasihat Kadin Indonesia untuk periode 2024-2029. Keputusan ini diumumkan melalui SK yang dibacakan oleh Wakil Ketua Umum Koordinator (WKUK) Bidang Organisasi, Komunikasi, dan Pemberdayaan Daerah Kadin Indonesia, Erwin Aksa.Bagaimana menurut mu?🙋#wartaekonomi #kadinindonesia #hajiisa #ptjhonlingroup",
                "comments": 111,
                "likes": 2,
                "shares": "",
                "favorites": "",
                "reposts": "",
                "views": "",
                "retweets": "",
                "replies": "",
                "votes": "",
                "user_image_url": "https://instagram.fbdo9-1.fna.fbcdn.net/v/t39.30808-6/484035071_1204057198388736_2427565160997191251_n.jpg?stp=dst-jpg_e35_tt6&efg=eyJ2ZW5jb2RlX3RhZyI6ImltYWdlX3VybGdlbi4xMDgweDEzNTAuc2RyLmYzMDgwOC5kZWZhdWx0X2ltYWdlIn0&_nc_ht=instagram.fbdo9-1.fna.fbcdn.net&_nc_cat=100&_nc_oc=Q6cZ2AFQCdhvxXTGZRkmKMLjR69_w3jWmBcYlzF4N1hgJSHM3-_TM7a0Gdj_TEo8L7724U4&_nc_ohc=XbhQwazcSCIQ7kNvgERvh__&_nc_gid=DN5wEc-6hLK-g7fBd6dC8w&edm=APs17CUAAAAA&ccb=7-5&ig_cache_key=MzU4Nzk5OTMxMjE2MTA2MzI4NQ%3D%3D.3-ccb7-5&oh=00_AYETlbsSwrL5L89FsG2z9fnSIJpCmfhYf08gJkSm39tj7Q&oe=67DE4BDD&_nc_sid=10d13b",
                "viral_score": 95.53478738466873,
                "post_created_at": "2025-03-14 09:01:13",
                "sentiment": "neutral",
                "channel": "instagram"
                },
                {
                "username": "r/KGBTR/",
                "followers_user": "",
                "likes_user": "",
                "influence_score": "",
                "link_post": "https://www.reddit.com/r/KGBTR/comments/wjzvvs/beyler_eskort_çağirdiniz_kadin_kapiya_kadar_geldi/",
                "post_caption": "BEYLER ESKORT ÇAĞIRDINIZ KADIN KAPIYA KADAR GELDİ DELİKTEN BAKTINIZ YARRAK GİBİ BİSEY VAADEDİLEN ŞEKİLDE DEİL NE YAPARDINIZ",
                "comments": 143,
                "likes": 105,
                "shares": 5,
                "favorites": 10,
                "reposts": 0,
                "views": 0,
                "retweets": 0,
                "replies": 0,
                "votes": 0,
                "user_image_url": "https://styles.redditmedia.com/t5_12t6sw/styles/communityIcon_qff9s3h0z8wc1.png",
                "viral_score": 85.91468166786318,
                "post_created_at": "2022-08-09 10:32:41",
                "sentiment": "negative",
                "channel": "reddit"
                },
                {
                "username": "r/Turkey/",
                "followers_user": "",
                "likes_user": "",
                "influence_score": "",
                "link_post": "https://www.reddit.com/r/Turkey/comments/1j3e7do/türkiyede_kadin_olmak/",
                "post_caption": "Türkiye'de kadin olmak",
                "comments": 197,
                "likes": 483,
                "shares": 24,
                "favorites": 48,
                "reposts": 0,
                "views": 0,
                "retweets": 0,
                "replies": 0,
                "votes": 0,
                "user_image_url": "https://styles.redditmedia.com/t5_2qlnu/styles/communityIcon_bzauhzh14wrc1.png",
                "viral_score": 85.1262897217239,
                "post_created_at": "2025-03-04 16:06:51",
                "sentiment": "neutral",
                "channel": "reddit"
                },
                {
                "username": "r/AteistTurk/",
                "followers_user": "",
                "likes_user": "",
                "influence_score": "",
                "link_post": "https://www.reddit.com/r/AteistTurk/comments/ubqjms/kitaplari_emir_ediyo_diye_4_kisi_bir_kadina/",
                "post_caption": "kitaplari emir ediyo diye 4 kisi bir kadina vuruyorlar sonra tatli su müslümanlari islam da kadin haklari var islam kadini yüceltiyor bu gercek islam degil diyorlar yazik gercekten yazik",
                "comments": 183,
                "likes": 438,
                "shares": 22,
                "favorites": 44,
                "reposts": 0,
                "views": 0,
                "retweets": 0,
                "replies": 0,
                "votes": 0,
                "user_image_url": "https://styles.redditmedia.com/t5_36iafd/styles/communityIcon_v6m1nrtccwrc1.jpg?format=pjpg&s=b2bfd56e70c8098e246f1fbdd483402c180bd12e",
                "viral_score": 80.05150571195395,
                "post_created_at": "2022-04-25 17:29:43",
                "sentiment": "negative",
                "channel": "reddit"
                },
                {
                "username": "r/burdurland/",
                "followers_user": "",
                "likes_user": "",
                "influence_score": "",
                "link_post": "https://www.reddit.com/r/burdurland/comments/hv2d65/kadin_hiç_yaşlanmıyor/",
                "post_caption": "Kadin hiç yaşlanmıyor.",
                "comments": 60,
                "likes": 1867,
                "shares": 93,
                "favorites": 187,
                "reposts": 0,
                "views": 0,
                "retweets": 0,
                "replies": 0,
                "votes": 0,
                "user_image_url": "https://styles.redditmedia.com/t5_yvsv4/styles/communityIcon_hdphoxhgrvo21.jpg?format=pjpg&s=afc2d856f603592e03934a1dbbe12a5062fa8dd6",
                "viral_score": 77.29349012678941,
                "post_created_at": "2020-07-21 06:25:48",
                "sentiment": "positive",
                "channel": "reddit"
                },
                {
                "username": "r/vlandiya/",
                "followers_user": "",
                "likes_user": "",
                "influence_score": "",
                "link_post": "https://www.reddit.com/r/vlandiya/comments/1cg7xn9/sizce_bu_kadin_kaşar_miydi_yoksa_hakli_miydi/",
                "post_caption": "SİZCE BU KADIN KAŞAR MIYDI YOKSA HAKLI MIYDI?",
                "comments": 131,
                "likes": 105,
                "shares": 5,
                "favorites": 10,
                "reposts": 0,
                "views": 0,
                "retweets": 0,
                "replies": 0,
                "votes": 0,
                "user_image_url": "https://styles.redditmedia.com/t5_8ldr9o/styles/communityIcon_s49eidku4hme1.png",
                "viral_score": 76.20545566940288,
                "post_created_at": "2024-04-29 19:26:40",
                "sentiment": "negative",
                "channel": "reddit"
                },
                {
                "username": "r/WithoutATrace/",
                "followers_user": "",
                "likes_user": "",
                "influence_score": "",
                "link_post": "https://www.reddit.com/r/WithoutATrace/comments/18q7d85/nineteen_year_old_kadin_black_has_been_missing/",
                "post_caption": "Nineteen year old Kadin Black has been missing for over a year. His strange disappearance is now being looked into by the FBI.",
                "comments": 141,
                "likes": 599,
                "shares": 30,
                "favorites": 60,
                "reposts": 0,
                "views": 0,
                "retweets": 0,
                "replies": 0,
                "votes": 0,
                "user_image_url": "https://styles.redditmedia.com/t5_2x0wl/styles/communityIcon_dh2opz3yrf1e1.png",
                "viral_score": 66.33150030300584,
                "post_created_at": "2023-12-25 00:16:42",
                "sentiment": "negative",
                "channel": "reddit"
                },
                {
                "username": "r/KGBTR/",
                "followers_user": "",
                "likes_user": "",
                "influence_score": "",
                "link_post": "https://www.reddit.com/r/KGBTR/comments/zxemtd/bune_şimdi_orospu_cocuklari_sizin_seriatcilardan/",
                "post_caption": "Bune şimdi orospu cocuklari sizin seriatcilardan ne farkiniz kaldi hem ortununce ninja kara prens diyorsunuz açık giyinince taşkınlık namussuzluk yapıyorsunuz kadin normal bir şekulde ders anlatıyor bunu atanında yorum yazan aq cocuklarininda aminakoim",
                "comments": 61,
                "likes": 1421,
                "shares": 71,
                "favorites": 142,
                "reposts": 0,
                "views": 0,
                "retweets": 0,
                "replies": 0,
                "votes": 0,
                "user_image_url": "https://styles.redditmedia.com/t5_12t6sw/styles/communityIcon_qff9s3h0z8wc1.png",
                "viral_score": 66.05239671978906,
                "post_created_at": "2022-12-28 16:58:06",
                "sentiment": "negative",
                "channel": "reddit"
                },
                {
                "username": "r/CollegeBasketball/",
                "followers_user": "",
                "likes_user": "",
                "influence_score": "",
                "link_post": "https://www.reddit.com/r/CollegeBasketball/comments/123wk6e/virginia_c_kadin_shedrick_has_entered_the/",
                "post_caption": "Virginia C Kadin Shedrick has entered the transfer portal. 6.2 PPG/3.8 RPG/1.4 BPG. Grad transfer.",
                "comments": 92,
                "likes": 54,
                "shares": 3,
                "favorites": 5,
                "reposts": 0,
                "views": 0,
                "retweets": 0,
                "replies": 0,
                "votes": 0,
                "user_image_url": "https://styles.redditmedia.com/t5_2rj3j/styles/communityIcon_yy1iggjp13jb1.png",
                "viral_score": 64.64087948179714,
                "post_created_at": "2023-03-27 18:56:01",
                "sentiment": "neutral",
                "channel": "reddit"
                },
                {
                "username": "r/KGBTR/",
                "followers_user": "",
                "likes_user": "",
                "influence_score": "",
                "link_post": "https://www.reddit.com/r/KGBTR/comments/1bvo5tv/kadin_dusmanligi_midir/",
                "post_caption": "KADIN DUSMANLIGI MIDIR???????",
                "comments": 124,
                "likes": 221,
                "shares": 11,
                "favorites": 22,
                "reposts": 0,
                "views": 0,
                "retweets": 0,
                "replies": 0,
                "votes": 0,
                "user_image_url": "https://styles.redditmedia.com/t5_12t6sw/styles/communityIcon_qff9s3h0z8wc1.png",
                "viral_score": 58.285133829133244,
                "post_created_at": "2024-04-04 14:12:20",
                "sentiment": "negative",
                "channel": "reddit"
                },
                {
                "username": "r/KGBTR/",
                "followers_user": "",
                "likes_user": "",
                "influence_score": "",
                "link_post": "https://www.reddit.com/r/KGBTR/comments/vtwypr/bu_kadin_hakkında_ne_dusunuyosunuz/",
                "post_caption": "Bu kadin hakkında ne dusunuyosunuz",
                "comments": 101,
                "likes": 100,
                "shares": 5,
                "favorites": 10,
                "reposts": 0,
                "views": 0,
                "retweets": 0,
                "replies": 0,
                "votes": 0,
                "user_image_url": "https://styles.redditmedia.com/t5_12t6sw/styles/communityIcon_qff9s3h0z8wc1.png",
                "viral_score": 55.79962940212016,
                "post_created_at": "2022-07-08 00:06:36",
                "sentiment": "neutral",
                "channel": "reddit"
                },
                {
                "username": "r/indonesia/",
                "followers_user": "",
                "likes_user": "",
                "influence_score": "",
                "link_post": "https://www.reddit.com/r/indonesia/comments/1fixdsu/jet_pribadi_dan_kadin/",
                "post_caption": "Jet pribadi dan kadin",
                "comments": 22,
                "likes": 0,
                "shares": 0,
                "favorites": 0,
                "reposts": 0,
                "views": 0,
                "retweets": 0,
                "replies": 0,
                "votes": 0,
                "user_image_url": "https://styles.redditmedia.com/t5_2qkte/styles/communityIcon_fly81d3k0ij21.png",
                "viral_score": 53.52119385257662,
                "post_created_at": "2024-09-17 12:04:23",
                "sentiment": "neutral",
                "channel": "reddit"
                },
                {
                "username": "r/bioniclememes/",
                "followers_user": "",
                "likes_user": "",
                "influence_score": "",
                "link_post": "https://www.reddit.com/r/bioniclememes/comments/o04zfd/think_greg_think_why_would_toa_wear_a_miru_if/",
                "post_caption": "Think Greg THINK! Why would Toa wear a Miru if they could have a Kadin instead?",
                "comments": 89,
                "likes": 626,
                "shares": 31,
                "favorites": 63,
                "reposts": 0,
                "views": 0,
                "retweets": 0,
                "replies": 0,
                "votes": 0,
                "user_image_url": "https://styles.redditmedia.com/t5_3gbar/styles/communityIcon_g0o3bnjboc831.png",
                "viral_score": 51.28356945275287,
                "post_created_at": "2021-06-15 03:49:39",
                "sentiment": "neutral",
                "channel": "reddit"
                }
            ]
            }

    try:
        result = list_of_mentions(
            keyword=request.keyword,
            sentiment=request.sentiment,
            date_filter=request.date_filter,
            custom_start_date=request.custom_start_date,
            custom_end_date=request.custom_end_date,
            channel=request.channel,
            influence_score_min=request.influence_score_min,
            influence_score_max=request.influence_score_max,
            region=request.region,
            language=request.language,
            importance=request.importance,
            domain=request.domain,
            sort_by=request.sort_by,
            limit=request.limit,
            offset=request.offset
        )

        # Sanitize the data to handle non-JSON-compliant float values
        sanitized_result = sanitize_data(result)

        return {
            "status": "success",
            "data": sanitized_result
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
